/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:baa66ac3-d21b-4aa0-8963-75cce85be4d1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kreIMhsga",
    "aws_user_pools_web_client_id": "2nv1qa5pionqmnsu5r7icm4fqt",
    "oauth": {}
};


export default awsmobile;
